from enum import Enum

class HurstMethodType(Enum):
    """
    Define the mapping between an estimation method and its implementation.
    """
    SCALING_VARIANCE = ...
    SCALED_WINDOWED_VARIANCE = ...
    AGGREGATE_VARIANCE = ...
    DFA_ANALYSIS = ...
    RS_ANALYSIS = ...
